import React, { createContext } from 'react'

const NewsContext = createContext({
    headlineHomeArticles: {},
    sideHomeArticles: {},
    headlineBusinessArticles: {},
    sideBusinessArticles: {},
    headlineHealthArticles: {},
    sideHealthArticles: {},
    headlineMediaArticles: {},
    sideMediaArticles: {},
    headlineScienceArticles: {},
    sideScienceArticles: {},
    headlineSportsArticles: {},
    sideSportsArticles: {},
    headlineTechArticles: {},
    sideTechArticles: {},
    loading: true,
    homeCount: 1,
    setHomeCount: homeCount => {},
    businessCount: 1,
    setBusinessCount: businessCount => {},
    healthCount: 1,
    setHealthCount: healthCount => {},
    mediaCount: 1,
    setMediaCount: mediaCount => {},
    scienceCount: 1,
    setScienceCount: scienceCount => {},
    sportsCount: 1,
    setSportsCount: sportsCount => {},
    techCount: 1,
    setTechCount: techCount => {},
});

export default NewsContext;